# Generated by Django 5.1.1 on 2024-10-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localSaida', models.CharField(blank=True, max_length=30, null=True)),
                ('localChegada', models.CharField(blank=True, max_length=30, null=True)),
                ('dataHora', models.DateTimeField(blank=True, null=True)),
                ('vagas', models.IntegerField(default=4, null=True)),
                ('adicionais', models.CharField(blank=True, default='', max_length=254)),
                ('dataModificacao', models.DateTimeField(auto_now_add=True)),
                ('materia', models.CharField(blank=True, max_length=10)),
                ('local', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('atividade', models.CharField(blank=True, max_length=30)),
                ('interesses', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
