# Generated by Django 5.1.1 on 2024-10-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
