# Generated by Django 5.1.1 on 2024-10-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApp', '0002_atividade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
