# Generated by Django 5.1.1 on 2024-10-13 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('psiuApp', '0004_atividade_criador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('vagas', models.IntegerField(default=4)),
                ('adicionais', models.CharField(max_length=254)),
                ('local', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('localSaida', models.CharField(max_length=30)),
                ('localChegada', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConhecerPessoas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('vagas', models.IntegerField(default=4)),
                ('adicionais', models.CharField(max_length=254)),
                ('local', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('topico', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('vagas', models.IntegerField(default=4)),
                ('adicionais', models.CharField(max_length=254)),
                ('local', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('materia', models.CharField(max_length=10)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extracurriculares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('vagas', models.IntegerField(default=4)),
                ('adicionais', models.CharField(max_length=254)),
                ('local', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('atividade', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('vagas', models.IntegerField(default=4)),
                ('adicionais', models.CharField(max_length=254)),
                ('local', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
