# Generated by Django 5.1.1 on 2024-10-13 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApp', '0005_carona_conhecerpessoas_estudos_extracurriculares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conhecerpessoas',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='estudos',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='extracurriculares',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='participacaoatividade',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='participacaoatividade',
            name='participante',
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localSaida', models.CharField(blank=True, max_length=30, null=True)),
                ('localChegada', models.CharField(blank=True, max_length=30, null=True)),
                ('dataHora', models.DateTimeField(blank=True, null=True)),
                ('vagas', models.IntegerField(default=4, null=True)),
                ('adicionais', models.CharField(blank=True, default='', max_length=254)),
                ('dataModificacao', models.DateTimeField(auto_now_add=True)),
                ('materia', models.CharField(blank=True, max_length=10)),
                ('local', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('atividade', models.CharField(blank=True, max_length=30)),
                ('interesses', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(max_length=15, null=True)),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psiuApp.atividade')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Carona',
        ),
        migrations.DeleteModel(
            name='ConhecerPessoas',
        ),
        migrations.DeleteModel(
            name='Estudos',
        ),
        migrations.DeleteModel(
            name='Extracurriculares',
        ),
        migrations.DeleteModel(
            name='Ligas',
        ),
        migrations.DeleteModel(
            name='ParticipacaoAtividade',
        ),
    ]
