# Generated by Django 5.1.1 on 2024-10-13 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiuApp', '0006_remove_conhecerpessoas_criador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='localSaida',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='localChegada',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='adicionais',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='dataModificacao',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='interesses',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='criador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApp.atividade')),
                ('localSaida', models.CharField(blank=True, max_length=30, null=True, verbose_name='Local de Saída')),
                ('localChegada', models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=('psiuApp.atividade',),
        ),
        migrations.CreateModel(
            name='ConhecerPessoas',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApp.atividade')),
                ('atividade', models.CharField(blank=True, max_length=30)),
            ],
            bases=('psiuApp.atividade',),
        ),
        migrations.CreateModel(
            name='Estudos',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApp.atividade')),
                ('materia', models.CharField(blank=True, max_length=10)),
            ],
            bases=('psiuApp.atividade',),
        ),
        migrations.CreateModel(
            name='Extracurriculares',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApp.atividade')),
                ('atividade', models.CharField(blank=True, max_length=30)),
                ('adicionais', models.CharField(blank=True, default='', max_length=254)),
            ],
            bases=('psiuApp.atividade',),
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psiuApp.atividade')),
                ('nome', models.CharField(blank=True, max_length=30)),
            ],
            bases=('psiuApp.atividade',),
        ),
    ]
